version: '3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./porcigest:/porcigest
    ports:
      - "8000:8000"
