version: '3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django:/django
    ports:
      - "8000:8000"
    depends_on:
      - db

  django-rpi:
    build:
      context: .
      dockerfile: Dockerfile_rpi
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django:/django
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "5432:5432"
    # command: ["postgres", "-c", "log_statement=all"]
